USE sakila;

-- 1. Number of films per category
SELECT
    c.name AS category,
    COUNT(fc.film_id) AS number_of_films
FROM category c
JOIN film_category fc
    ON c.category_id = fc.category_id
GROUP BY c.name
ORDER BY number_of_films DESC;


-- 2. Store ID, city, and country for each store
SELECT
    s.store_id,
    ci.city,
    co.country
FROM store s
JOIN address a
    ON s.address_id = a.address_id
JOIN city ci
    ON a.city_id = ci.city_id
JOIN country co
    ON ci.country_id = co.country_id;
    
    -- 3. Total revenue generated by each store
SELECT
    s.store_id,
    ROUND(SUM(p.amount), 2) AS total_revenue
FROM store s
JOIN staff st
    ON s.store_id = st.store_id
JOIN payment p
    ON st.staff_id = p.staff_id
GROUP BY s.store_id
ORDER BY s.store_id;


-- 4. Average running time of films for each category
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category c
JOIN film_category fc
    ON c.category_id = fc.category_id
JOIN film f
    ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC;

-- Bonus 5. Category with the longest average running time
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category c
JOIN film_category fc
    ON c.category_id = fc.category_id
JOIN film f
    ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC
LIMIT 1;

-- Bonus 6. Top 10 most frequently rented movies
SELECT
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM film f
JOIN inventory i
    ON f.film_id = i.film_id
JOIN rental r
    ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC
LIMIT 10;

-- Bonus 7. Check if Academy Dinosaur can be rented from Store 1
SELECT
    f.title,
    i.store_id,
    i.inventory_id
FROM film f
JOIN inventory i
    ON f.film_id = i.film_id
WHERE f.title = 'ACADEMY DINOSAUR'
  AND i.store_id = 1;
  
  -- Bonus 8. Film titles with availability status
SELECT
    f.title,
    CASE
        WHEN IFNULL(i.inventory_id, 0) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability
FROM film f
LEFT JOIN inventory i
    ON f.film_id = i.film_id
GROUP BY f.film_id, f.title, availability
ORDER BY f.title;